---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tictacla/web_folder
    - export PUBLIC_HTML_PATH=/home/tictacla/public_html
    - export PHP_PATH=/usr/local/bin/ea-php83
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -a * $DEPLOYPATH
    - cd $DEPLOYPATH
    - /bin/rm -rf .git
    - /bin/rm -rf .github
    - /bin/rm -rf .vscode
    - /bin/rm -rf .cpanel.yml
    - /bin/ln -s $DEPLOYPATH/public/index.php $PUBLIC_HTML_PATH/index.php
    - /bin/ln -s $DEPLOYPATH/storage/app/public $PUBLIC_HTML_PATH/storage
    - /bin/ln -s $DEPLOYPATH/public/.htaccess $PUBLIC_HTML_PATH/.htaccess
    - /bin/ln -s $DEPLOYPATH/public/favicon.ico $PUBLIC_HTML_PATH/favicon.ico
    - /bin/ln -s $DEPLOYPATH/public/robots.txt $PUBLIC_HTML_PATH/robots.txt
    - /bin/cp $DEPLOYPATH/public/img $PUBLIC_HTML_PATH/img
    - $PHP_PATH ~/bin/composer install --no-dev --optimize-autoloader
    - $PHP_PATH artisan config:cache
    - $PHP_PATH artisan route:cache
    - $PHP_PATH artisan view:cache
    - $PHP_PATH artisan optimize:clear
    - $PHP_PATH artisan storage:link
